name: Docker image ci GHCR

on:
  pull_request:
    branches:
      - main # Ou o branch de destino que você usa para gerenciar releases
    types:
      - closed

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para o workflow criar tags

    steps:
      - uses: actions/checkout@v3

      - name: Configuração do Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Instalar dependências
        run: npm install

      - name: Criar release com release-it
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Obter tag criada pelo release-it
        id: extract_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build e push da imagem Docker
        run: |
          docker login --username maikonalexandre --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/maikonalexandre/github-packages-example:${{ env.TAG }}
          docker push ghcr.io/maikonalexandre/github-packages-example:${{ env.TAG }}
