name: Docker image ci GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm install
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push image
        run: |
          docker login --username maikonalexandre --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/maikonalexandre/github-packages-example:${{ env.TAG }}
          docker push ghcr.io/maikonalexandre/github-packages-example:${{ env.TAG }}
